//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }
        public decimal Price { get; set; }
        public string FoodType { get; set; }
        public System.DateTime BoughtDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime ManufacturedDate { get; set; }
    }
}
