//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public string Email { get; set; }
        public int Persons { get; set; }
        public System.DateTime Date { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string Menu1 { get; set; }
        public string Menu2 { get; set; }
        public string Menu3 { get; set; }
        public string Menu4 { get; set; }
        public string Menu5 { get; set; }
        public decimal Total { get; set; }
        public string Details { get; set; }
    }
}
