//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    
    public partial class Sale
    {
        public int SalesId { get; set; }
        public DateTime Date { get; set; }
        public decimal Income { get; set; }
        public decimal Expenditure { get; set; }
        public decimal Profit { get; set; }
    }
}
